# Generated by Django 4.2.1 on 2023-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('discount_percent', models.IntegerField()),
            ],
        ),
    ]
