# Generated by Django 4.2.1 on 2023-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_discountcode_delete_discountcodes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_code_applied",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
