# Generated by Django 4.2.1 on 2023-06-10 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_order_discount_code_applied"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscountCode",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_code_applied",
        ),
    ]
