"""datetime to strin

Revision ID: 587d7da8af25
Revises: c4615c235a77
Create Date: 2023-05-22 15:39:08.283605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587d7da8af25'
down_revision = 'c4615c235a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    # ### end Alembic commands ###
