"""MODEL UPDATE

Revision ID: a62445537ecc
Revises: dbd996effbda
Create Date: 2023-05-22 20:57:48.285661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62445537ecc'
down_revision = 'dbd996effbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('logg_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('logg_status')
        batch_op.drop_column('register_time')

    # ### end Alembic commands ###
