"""datetime to string

Revision ID: dbd996effbda
Revises: 587d7da8af25
Create Date: 2023-05-22 15:48:06.747893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbd996effbda'
down_revision = '587d7da8af25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post_datetime',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('time_edited',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('time_edited',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('post_datetime',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
